title: Pensiero andando
name: Carlo Fusari
user_description: studente di management che cerca di pensare in maniera organizzata
notes_url: "http://www.carlofusari.com/"
profile_pic: C:\Users\carlo\OneDrive\Desktop\4. Archivio\Carlo\Curriculum e altro
favicon: /assets/img/favicon.png
copyright_name: Carlo Fusari
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.carlofusari.com//" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /notes/:title

disqus:
  shortname: raghuveerdotnet

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
